#!/usr/bin/env bash

set -e
set -x

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Get standard environment variables
PRGDIR=`dirname "$PRG"`

DOT_ENV_RC="$PRGDIR/.envrc"

# SOURCE .ENVRC IF EXISTS
if [ -f $DOT_ENV_RC ];
then
   source $DOT_ENV_RC
else
   echo "File $DOT_ENV_RC does not exist."
fi

pushd $PRGDIR

mkdir -p target/test/

export AWS_DEFAULT_OUTPUT="json"

aws lambda invoke \
--invocation-type Event \
--function-name CreateThumbnail \
--payload file://./src/test/input.json \
target/test/outputfile.json